### PR TITLE
System Specification Updates

### PR DESCRIPTION
**Pull request by lboeman**
Handles Issues brought up in #88 particular to the System Specification page.

- Tabbing should skip help boxes. Removed the help buttons from the tab index, so that they aren't accessible via keyboard. Added some ARIA attributes to describe the inputs using the help text when using screenreaders, since the buttons would no longer be accessible.
- Elevation lookup button via google maps javascript api/elevation service. Requires that an api key be specified using the VUE_APP_GOOGLE_MAPS_API_KEY environment variable. Button can be seen below (with the fun -3492 result at lat/lon 0,0). Maybe best below/next to the elevation input?  
  Screenshot from 2021-01-22 12-49-13

- Removed the default system name. Inverters and Array should be added with incrementing names e.g. "Inverter 1", "Invereter 2". 
  ~~Need to fix bug where removing and adding an inverter/array results in same name. e.g. add "Inverter 1", "Invereter 2", delete inverter 1 and add a second invereter 2.~~ This is actually less confusing then adding adding a second inverter and getting "Inverter 7" or something. 
- Moved JSON summary toggle to a collapsible block.
  Screenshot from 2021-01-22 12-47-58

- PVWatts Lid => LID. This is the only change in `models.py`

Needs tests and I'll add the follow functionality from #92 here as well.

### CODE REVIEW

**Review by alorenzo175 — COMMENTED** [review]
I would prefer the elevation button next to the elevation field. 

When clicking on a single axis tracker I get this console error
```
[Vue warn]: Property or method "fieldID" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <ModelField> at src/components/ModelField.vue
       <TrackingParametersView> at src/components/model/TrackingParameters.vue
         <ArrayView> at src/components/model/Array.vue
           <ArraysView> at src/components/model/Arrays.vue
             <InverterView> at src/components/model/Inverter.vue
               <InvertersView> at src/components/model/Inverters.vue
                 <SystemView> at src/components/model/System.vue
                   <SystemSpec> at src/views/SystemSpec.vue
                     <Home> at src/views/Home.vue
                       <App> at src/App.vue
                         <Root> vue.runtime.esm.js:619
    VueJS 3
    render ModelField.vue:98
    VueJS 29
    change Array.vue:82
    VueJS 33
```

**Review by alorenzo175 — APPROVED** [review]

**Comment by lboeman** [comment]
Updated to use https://nationalmap.gov/epqs/ over Google maps to avoid any handling of keys. Only really covers Continental U.S. but would be easy in the future to integrate a different service.

**Comment by lboeman** [comment]
@alorenzo175 updated `dashboard/src/utils/elevation.ts` since approval. Still good to merge with you?

**Review by alorenzo175 — APPROVED** [review]

**Comment by wholmgren** [comment]
@ncroft-b4 thanks for the https://nationalmap.gov/epqs/  suggestion!

**Pull request merged**
