### PR TITLE
Allow no header CSV

### LINKED ISSUE #158: Allow CSVs without a header
maybe if CSV header row is 0, then don't use any header row

### PR DESCRIPTION
**Pull request by lboeman**
Allows users to set the header row to 0, and creates some stub headers like "Column 1, Column 2" etc.
closes #158

### CODE REVIEW

**Comment by lboeman** [comment]
This now allows for missing headers by setting the header line to 0. I've added a help box to assist users in utilizing this. Also fixes a bug that @wholmgren brought up, where a file without an index (time) header fails to parse/post correctly. Parsing can now allow for a single empty header, because "" is a valid object key. I've added a validation step to check CSVs for duplicate headers, as they would not raise an error but would cause unexpected behavior when posting.

@alorenzo175 Can you give this a quick poke?

**Comment by alorenzo175** [comment]
Is this supposed to happen in Data Rows? 
image

**Comment by lboeman** [comment]
> Is this supposed to happen in Data Rows? csv headers = 0
> image

Nope, thanks. Caused by last minute debugging junk.

**Review by wholmgren — APPROVED** [review]
we'll fix any bugs in production, er dev

**Pull request merged**
